-- ============================================================
-- FIX MIGRATION: Add missing columns
-- Run this if dashboard shows error
-- ============================================================

-- Add user_name to transactions if not exists
DROP PROCEDURE IF EXISTS add_col_if_not_exists;
DELIMITER $$
CREATE PROCEDURE add_col_if_not_exists()
BEGIN
  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'transactions' AND COLUMN_NAME = 'user_name'
  ) THEN
    ALTER TABLE transactions ADD COLUMN user_name VARCHAR(100) DEFAULT NULL;
  END IF;

  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'transactions' AND COLUMN_NAME = 'created_at'
  ) THEN
    ALTER TABLE transactions ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
  END IF;

  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'transactions' AND COLUMN_NAME = 'payment_method'
  ) THEN
    ALTER TABLE transactions ADD COLUMN payment_method VARCHAR(20) DEFAULT 'cash';
  END IF;

  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'transactions' AND COLUMN_NAME = 'customer_name'
  ) THEN
    ALTER TABLE transactions ADD COLUMN customer_name VARCHAR(100) DEFAULT NULL;
  END IF;

  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'transactions' AND COLUMN_NAME = 'customer_id'
  ) THEN
    ALTER TABLE transactions ADD COLUMN customer_id INT DEFAULT NULL;
  END IF;

  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'transactions' AND COLUMN_NAME = 'discount'
  ) THEN
    ALTER TABLE transactions ADD COLUMN discount DECIMAL(15,2) DEFAULT 0;
  END IF;

  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'transactions' AND COLUMN_NAME = 'subtotal'
  ) THEN
    ALTER TABLE transactions ADD COLUMN subtotal DECIMAL(15,2) DEFAULT 0;
  END IF;

  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'transactions' AND COLUMN_NAME = 'notes'
  ) THEN
    ALTER TABLE transactions ADD COLUMN notes TEXT DEFAULT NULL;
  END IF;

  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'products' AND COLUMN_NAME = 'category_id'
  ) THEN
    ALTER TABLE products ADD COLUMN category_id INT DEFAULT NULL;
  END IF;

  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'products' AND COLUMN_NAME = 'min_stock'
  ) THEN
    ALTER TABLE products ADD COLUMN min_stock INT DEFAULT 5;
  END IF;

  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'products' AND COLUMN_NAME = 'image_url'
  ) THEN
    ALTER TABLE products ADD COLUMN image_url VARCHAR(500) DEFAULT NULL;
  END IF;

  IF NOT EXISTS (
    SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'transaction_items' AND COLUMN_NAME = 'discount'
  ) THEN
    ALTER TABLE transaction_items ADD COLUMN discount DECIMAL(15,2) DEFAULT 0;
  END IF;
END$$
DELIMITER ;

CALL add_col_if_not_exists();
DROP PROCEDURE IF EXISTS add_col_if_not_exists;

-- Ensure tables exist
CREATE TABLE IF NOT EXISTS categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  color VARCHAR(7) DEFAULT '#2563eb',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  points INT DEFAULT 0,
  total_transactions INT DEFAULT 0,
  total_spent DECIMAL(15,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shifts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  user_name VARCHAR(100) NOT NULL,
  opening_cash DECIMAL(15,2) DEFAULT 0,
  closing_cash DECIMAL(15,2) DEFAULT NULL,
  expected_cash DECIMAL(15,2) DEFAULT NULL,
  total_sales DECIMAL(15,2) DEFAULT 0,
  total_transactions INT DEFAULT 0,
  notes TEXT DEFAULT NULL,
  status ENUM('open', 'closed') DEFAULT 'open',
  opened_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS expenses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  user_id INT NOT NULL,
  user_name VARCHAR(100) NOT NULL,
  date DATE DEFAULT (CURRENT_DATE),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default categories if empty
INSERT IGNORE INTO categories (id, name, color) VALUES
  (1, 'Makanan', '#ef4444'),
  (2, 'Minuman', '#3b82f6'),
  (3, 'Snack', '#f59e0b'),
  (4, 'Lainnya', '#6b7280');
